# Generated by Django 4.2.2 on 2023-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Register User", "verbose_name_plural": "Registered Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="The contact number of the customer.",
                max_length=50,
                null=True,
                verbose_name="Contact Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="The first names of the customer.",
                max_length=255,
                null=True,
                verbose_name="First names",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="The first names of the customer.",
                max_length=255,
                null=True,
                verbose_name="Last names",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(default="0000", help_text="The PIN of the customer.", max_length=4),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The email address of the customer.",
                max_length=150,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
