# Generated by Django 4.2.2 on 2023-06-28 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Register User", "verbose_name_plural": "Registered Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="The contact number of the customer.",
                max_length=50,
                null=True,
                verbose_name="Contact Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country_of_residence",
            field=models.ForeignKey(
                blank=True,
                help_text="The country of residence of the customer. KYC Verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.country",
                verbose_name="Country of Residence",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="The birth date of the customer.", null=True, verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                blank=True,
                default="EUR",
                help_text="The default currency of the borrower. Currency will be sent against borrowers country of residence.",
                max_length=3,
                null=True,
                verbose_name="Default Currency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="The first names of the customer.",
                max_length=255,
                null=True,
                verbose_name="First names",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="The job title of the customer.",
                max_length=150,
                null=True,
                verbose_name="Job Title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="The first names of the customer.",
                max_length=255,
                null=True,
                verbose_name="Last names",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="place_of_birth",
            field=models.CharField(
                blank=True,
                help_text="The place of birth of the customer. This must match the place of birth as indicated in the customers photo Identitication.",
                max_length=150,
                null=True,
                verbose_name="Place of Birth",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registered_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                editable=False,
                help_text="The IP address recorded at the time of registration.",
                null=True,
                verbose_name="Registered IP Address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_security_number",
            field=models.CharField(
                blank=True,
                help_text="The social security number of the customer. This helps to determine the credit score and also validates the identity of the customer.",
                max_length=50,
                null=True,
                verbose_name="Social Security Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp when customers profile was verified.",
                null=True,
                verbose_name="Verification Date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The email address of the customer.",
                max_length=150,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier of the customer.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("current", "Current Address"), ("permanent", "Permanent Address")],
                        default="current",
                        help_text="The type of address.",
                        max_length=9,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="Address line 2 of the user", max_length=50, verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address line 2 of the user",
                        max_length=50,
                        null=True,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Address line 2 of the user", max_length=50, verbose_name="State or Region"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="The city of the address of the user.", max_length=50, verbose_name="City"
                    ),
                ),
                (
                    "zip_post_code",
                    models.CharField(
                        help_text="The zip or Postal code of the address of the user.",
                        max_length=20,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Enter field documentation",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user for whom address belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="current_address",
            field=models.ForeignKey(
                blank=True,
                help_text="The current living address of the customer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.useraddress",
                verbose_name="Current Address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="permanent_address",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent address of the customer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.useraddress",
                verbose_name="Permanent Address",
            ),
        ),
    ]
