# Generated by Django 4.2.2 on 2023-07-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kyc_complete",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Flag to determine if a cutomer have completed KYC verification",
                null=True,
                verbose_name="KYC complete",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_complete_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when customer completed KYC verifiction process.",
                null=True,
                verbose_name="KYC complete date",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("action_required", "Action_required"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected/Refused"),
                ],
                default="Unverified",
                help_text="The .",
                max_length=15,
                null=True,
                verbose_name="KYC status",
            ),
        ),
    ]
