# Generated by Django 4.2.2 on 2023-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
