# Generated by Django 4.2.2 on 2023-06-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_wallet_id"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="user",
        #     name="pin",
        #     field=models.CharField(blank=True, help_text="The PIN of the customer.", max_length=4, null=True),
        # ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(
                max_length=4,
                default='0000',
                help_text='The PIN of the customer.'
            ),
        ),


    ]
