# Generated by Django 4.2.2 on 2023-07-01 14:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Modified date when the record was created.",
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "card_number",
                    models.IntegerField(blank=True, help_text="Card number", null=True, verbose_name="cards"),
                ),
                (
                    "month",
                    models.IntegerField(blank=True, help_text="Card ecperiry month", null=True, verbose_name="month"),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, help_text="Card expiry year", null=True, verbose_name="year"),
                ),
                (
                    "card_name",
                    models.CharField(
                        blank=True, help_text="Card holder name", max_length=200, null=True, verbose_name="Card Name"
                    ),
                ),
                (
                    "cvv",
                    models.IntegerField(
                        blank=True, help_text="Card Verification Value", null=True, verbose_name="CVV"
                    ),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
    ]
