# Generated by Django 4.2.2 on 2023-07-05 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("card", "0003_bank_card_virtual_card_delete_virtualcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank_card",
            name="user",
            field=models.ForeignKey(
                default=2,
                help_text="ID of the card holder",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Card Owner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtual_card",
            name="user",
            field=models.ForeignKey(
                default=123456,
                help_text="ID of the card holder",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Card Owner",
            ),
            preserve_default=False,
        ),
    ]
