# Generated by Django 4.2.2 on 2023-07-05 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("card", "0004_bank_card_user_virtual_card_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bank_Card",
            new_name="BankCard",
        ),
        migrations.RenameModel(
            old_name="Virtual_Card",
            new_name="VirtualCard",
        ),
    ]
