# Generated by Django 4.2.2 on 2023-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0005_rename_bank_card_bankcard_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankcard",
            options={"verbose_name": "Bank Card", "verbose_name_plural": "Bank Cards"},
        ),
        migrations.RemoveField(
            model_name="bankcard",
            name="expiration_date",
        ),
        migrations.AddField(
            model_name="bankcard",
            name="expiry_date",
            field=models.CharField(
                default=23,
                help_text="The expiration date of the virtual card",
                max_length=4,
                verbose_name="Expiration Date",
            ),
            preserve_default=False,
        ),
    ]
