# Generated by Django 4.2.2 on 2023-07-05 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0006_alter_bankcard_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VirtualCard",
        ),
    ]
