# Generated by Django 4.2.2 on 2023-07-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Modified date when the record was created.",
                        verbose_name="Modified Date",
                    ),
                ),
                ("wallet_id", models.CharField(max_length=10, unique=True)),
                ("pin", models.CharField(default="0000", help_text="The PIN of the customer.", max_length=4)),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="The type of currency the wallet will operate on",
                        max_length=50,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Modified date when the record was created.",
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "deposit"), ("transfer", "transfer"), ("withdraw", "withdraw")],
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                ("status", models.CharField(default="pending", max_length=15)),
                ("reference", models.CharField(max_length=50)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet")),
            ],
            options={
                "verbose_name": "Wallet Transactions",
                "verbose_name_plural": "Wallet Transactions",
            },
        ),
    ]
