# Generated by Django 4.2.2 on 2023-06-30 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "deposit"), ("transfer", "transfer"), ("withdraw", "withdraw")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("status", models.CharField(default="pending", max_length=100)),
                ("paystack_payment_reference", models.CharField(blank=True, default="", max_length=100)),
                (
                    "wallet",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"),
                ),
            ],
            options={
                "verbose_name": "Wallet Transactions",
                "verbose_name_plural": "Wallet Transactions",
            },
        ),
    ]
