# Generated by Django 4.2.2 on 2023-07-01 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0002_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The time and date the card was created",
                null=True,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                default="NGN",
                help_text="The type of currency the wallet will operate on",
                max_length=50,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                help_text="Wallet information/ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The time and date the card was created",
                max_digits=100,
                null=True,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="paystack_payment_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The time and date the card was created",
                max_length=100,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                default="pending",
                help_text="The time and date the card was created",
                max_length=100,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The time and date the card was created",
                null=True,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "deposit"), ("transfer", "transfer"), ("withdraw", "withdraw")],
                help_text="The time and date the card was created",
                max_length=200,
                null=True,
                verbose_name="Time Created",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                help_text="The time and date the card was created",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
                verbose_name="Time Created",
            ),
        ),
    ]
