# Generated by Django 4.2.2 on 2023-06-28 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="State",
        ),
    ]
