# Generated by Django 4.2.2 on 2023-07-06 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycapplication",
            name="birth_date",
        ),
    ]
