# Generated by Django 4.2.2 on 2023-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycapplication",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="The birth date of the customer.", null=True, verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="kycapplication",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="The job title of the customer.",
                max_length=150,
                null=True,
                verbose_name="Job Title",
            ),
        ),
    ]
