# Generated by Django 4.2.2 on 2023-06-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_state"),
        ("kyc", "0002_kycapplication_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycapplication",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="The State/Region/Province of the user submitting KYC application. Must be from The user's country of Residence indicated at the time of registration.",
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.state",
                verbose_name="State/Region",
            ),
        ),
    ]
